[package]
name = "othello"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
coz = "0.1.3"
rand = "0.8.5"
statrs = "0.17.1"
tqdm = "0.7.0"

[profile.dev]
opt-level = 1
debug = true
